# Generated by Django 6.0.3 on 2026-04-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='students/profile_images/'),
        ),
    ]
