# Generated by Django 6.0.3 on 2026-05-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_tag_profile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='students/profile_images/'),
        ),
    ]
